import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppBar, Box, Button, Toolbar, Typography } from "@mui/material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar position="static" sx={{ backgroundColor: "#D9DDFF" }}>
          <Toolbar variant="dense">
            <Typography
              variant="h6"
              fontWeight="bold"
              fontStyle="italic"
              component={Link}
              href="/"
              sx={{ color: "#5F6FFF" }}
            >
              SPLTR.io
            </Typography>
            <Box sx={{ display: "flex", flex: 1, justifyContent: "end" }}>
              <Button
                variant="text"
                LinkComponent={Link}
                href="manage"
                sx={{ color: "white" }}
              >
                Manage
              </Button>
            </Box>
          </Toolbar>
        </AppBar>
        <Box sx={{ p: 2, height: "100%" }}>{children}</Box>
      </body>
    </html>
  );
}
